### ISSUE TITLE
Conveying video properties in a registration descriptor()

### ISSUE THREAD

**Issue by paulhiggs** [AOMediaCodec/av1-mpeg2-ts#27]
Is it really possible to convey the video properties per the ````AV1_video_descriptor()```` in the additional bytes of an ISO/IEC 13818-1 / ITU-T H.220.0 ````registration_descriptor```` which is what is interpreted from 'presence of a _Registration Descriptor, as defined in MPEG-2 TS_, ' and 'MPEG-2 Transport Stream specification, **ISO/IEC 13818-1:2018**'?
From 138
![registration_descriptor()](https://user-images.githubusercontent.com/3158807/195509850-0a861706-b2fe-4399-85f9-85b388cf0532.png)
18-1 8th edition...

This descriptor has ````descriptor_tag == 0x05```` (table 2-45).

[ETSI EN 300 465](https://www.etsi.org/deliver/etsi_en/300400_300499/300468/01.17.01_20/en_300468v011701a.pdf) has a ````private_data_specifier_descriptor```` with ````descriptor_tag=0x5f````. This descriptor needs to appear in the bitstream before any private defined descriptor that uses a ````descriptor_tag````  in the range 0x80~0xFE.

The value for the ````private_data_specifier```` element in the ````private_data_specifier_descriptor()```` needs to be obtained and registered with [DVB Services](https://www.dvbservices.com/identifiers/private_data_spec_id).

**Comment by cconcolato** [comment]
Thanks for the question Paul. There are 2 reasons the group thinks it's possible:
- this has been done for VC-1
- in the text you copied, it clearly says that the `additional_identification_info` bytes are defined by the assignee of the `format_identifier`
I'm not sure what you intended to mean with the additional text on `private_data_specifier`.

**Comment by paulhiggs** [comment]
OK, but the spec text also says

> Syntax	No. Of bits	Mnemonic
> registration_descriptor() {		
> descriptor_tag	8	uimsbf
> descriptor_length	8	uimsbf
> format_identifier	32	uimsbf
> AV1_video_descriptor()		
> }		
> descriptor_tag - This value shall be set to 0x5F.

0x5f is not the descriptor_tag for an ISO/IEC 13818 registration_descriptor()

**Comment by cconcolato** [comment]
Oh, nice catch! 0x5F should be 0x05. cc @tbiat @kierank

**Comment by tbiat** [comment]
This has been fixed in the last PR.
