### ISSUE TITLE
Clarify use of descriptor and change of sequence header OBU values

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-mpeg2-ts#35]
The current video descriptor semantics says things like:
> seq_profile, seq_level_idx_0 and high_bitdepth - These fields shall be coded according to the semantics defined in [[AV1]. If these fields are not coded in the Sequence Header OBU in the AV1 video stream, the inferred values are coded in the descriptor.

It is not clear if a new video descriptor is needed if a new Sequence Header OBU contains different values from a previous one. I suggest adding something like:
> If a value in a Sequence Header OBU differ from the value coded in the descriptor, a new video descriptor may be needed. For example, if the new seq_level_idx_0 is greater than the one given in the descriptor. The scope of a video descriptor is all access units starting after the PMT and starting before the next PMT.

For the example of "level", section 3.4 already says:
> The highest level that may occur in an AV1 video stream, as well as a profile and tier that the entire stream conforms to, shall be signalled using the AV1 video descriptor.

I think that sentence should be moved to the video descriptor section, and not be in the PES section.

Also, it probably should be written with statements can be more easily verified:
> * If a field XXX is coded in a Sequence Header OBU in the scope of the video descriptor, the field XXX in the video descriptor shall have the same value [TBD modify the sentence for fields where it can be different]
> * if a field XXX is not coded in a Sequence Header OBU in the scope of the video descriptor, the field XXX in the video descriptor shall be set to the value YYY as defined in the AV1 specification [TBD replace with the "inferred value"].

**Comment by kierank** [comment]
I think this is a fair point but IMO it's a constructive part of creating a TS. AVC does not mention anything about this particular problem.
