### ISSUE TITLE
OBU start code and OBU size are redundant

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-mpeg2-ts#7]
We should consider removing the size field when encapsulating into TS to avoid its overhead. OBU boundaries can be detected by start codes.

**Comment by tbiat** [comment]
Technically it's true with startcode we don't need the size anymore.
Could hurt existing av1 decoders that may need the size to work properly.
Leave it as it is would help with repackaging in a DVB context from TS to MP4 (HomeGateway / HomeBroadcast).
An OBU may contain an OBU size + Note : for applications that need easy conversion to MP4, using the OBU_size field is recommended.
Decision : adopt this wording.

**Comment by tbiat** [comment]
For applications that need conversion from MPEG2-TS to MP4, use of the *obu_size* field is recommended.
